[package]
name = "r2d2-test"
version = "0.1.0"
authors = ["袁殷 <2212079150@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

r2d2 = "0.8.9"
r2d2_mysql = "18.0.0"
mysql = "20.1.0"
